<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CommuneSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('communes')->truncate();
        DB::table('communes')->insert(
            [
                ['id' => 1101, 'name' => 'Iquique', 'province_id' => 11],
                ['id' => 1107, 'name' => 'Alto Hospicio', 'province_id' => 11],
                ['id' => 1401, 'name' => 'Pozo Almonte', 'province_id' => 14],
                ['id' => 1402, 'name' => 'Camiña', 'province_id' => 14],
                ['id' => 1403, 'name' => 'Colchane', 'province_id' => 14],
                ['id' => 1404, 'name' => 'Huara', 'province_id' => 14],
                ['id' => 1405, 'name' => 'Pica', 'province_id' => 14],
                ['id' => 2101, 'name' => 'Antofagasta', 'province_id' => 21],
                ['id' => 2102, 'name' => 'Mejillones', 'province_id' => 21],
                ['id' => 2103, 'name' => 'Sierra Gorda', 'province_id' => 21],
                ['id' => 2104, 'name' => 'Taltal', 'province_id' => 21],
                ['id' => 2201, 'name' => 'Calama', 'province_id' => 22],
                ['id' => 2202, 'name' => 'Ollagüe', 'province_id' => 22],
                ['id' => 2203, 'name' => 'San Pedro de Atacama', 'province_id' => 22],
                ['id' => 2301, 'name' => 'Tocopilla', 'province_id' => 23],
                ['id' => 2302, 'name' => 'María Elena', 'province_id' => 23],
                ['id' => 3101, 'name' => 'Copiapó', 'province_id' => 31],
                ['id' => 3102, 'name' => 'Caldera', 'province_id' => 31],
                ['id' => 3103, 'name' => 'Tierra Amarilla', 'province_id' => 31],
                ['id' => 3201, 'name' => 'Chañaral', 'province_id' => 32],
                ['id' => 3202, 'name' => 'Diego de Almagro', 'province_id' => 32],
                ['id' => 3301, 'name' => 'Vallenar', 'province_id' => 33],
                ['id' => 3302, 'name' => 'Alto del Carmen', 'province_id' => 33],
                ['id' => 3303, 'name' => 'Freirina', 'province_id' => 33],
                ['id' => 3304, 'name' => 'Huasco', 'province_id' => 33],
                ['id' => 4101, 'name' => 'La Serena', 'province_id' => 41],
                ['id' => 4102, 'name' => 'Coquimbo', 'province_id' => 41],
                ['id' => 4103, 'name' => 'Andacollo', 'province_id' => 41],
                ['id' => 4104, 'name' => 'La Higuera', 'province_id' => 41],
                ['id' => 4105, 'name' => 'Paiguano', 'province_id' => 41],
                ['id' => 4106, 'name' => 'Vicuña', 'province_id' => 41],
                ['id' => 4201, 'name' => 'Illapel', 'province_id' => 42],
                ['id' => 4202, 'name' => 'Canela', 'province_id' => 42],
                ['id' => 4203, 'name' => 'Los Vilos', 'province_id' => 42],
                ['id' => 4204, 'name' => 'Salamanca', 'province_id' => 42],
                ['id' => 4301, 'name' => 'Ovalle', 'province_id' => 43],
                ['id' => 4302, 'name' => 'Combarbalá', 'province_id' => 43],
                ['id' => 4303, 'name' => 'Monte Patria', 'province_id' => 43],
                ['id' => 4304, 'name' => 'Punitaqui', 'province_id' => 43],
                ['id' => 4305, 'name' => 'Río Hurtado', 'province_id' => 43],
                ['id' => 5101, 'name' => 'Valparaíso', 'province_id' => 51],
                ['id' => 5102, 'name' => 'Casablanca', 'province_id' => 51],
                ['id' => 5103, 'name' => 'Concón', 'province_id' => 51],
                ['id' => 5104, 'name' => 'Juan Fernández', 'province_id' => 51],
                ['id' => 5105, 'name' => 'Puchuncaví', 'province_id' => 51],
                ['id' => 5107, 'name' => 'Quintero', 'province_id' => 51],
                ['id' => 5109, 'name' => 'Viña del Mar', 'province_id' => 51],
                ['id' => 5201, 'name' => 'Isla de Pascua', 'province_id' => 52],
                ['id' => 5301, 'name' => 'Los Andes', 'province_id' => 53],
                ['id' => 5302, 'name' => 'Calle Larga', 'province_id' => 53],
                ['id' => 5303, 'name' => 'Rinconada', 'province_id' => 53],
                ['id' => 5304, 'name' => 'San Esteban', 'province_id' => 53],
                ['id' => 5401, 'name' => 'La Ligua', 'province_id' => 54],
                ['id' => 5402, 'name' => 'Cabildo', 'province_id' => 54],
                ['id' => 5403, 'name' => 'Papudo', 'province_id' => 54],
                ['id' => 5404, 'name' => 'Petorca', 'province_id' => 54],
                ['id' => 5405, 'name' => 'Zapallar', 'province_id' => 54],
                ['id' => 5501, 'name' => 'Quillota', 'province_id' => 55],
                ['id' => 5502, 'name' => 'Calera', 'province_id' => 55],
                ['id' => 5503, 'name' => 'Hijuelas', 'province_id' => 55],
                ['id' => 5504, 'name' => 'La Cruz', 'province_id' => 55],
                ['id' => 5506, 'name' => 'Nogales', 'province_id' => 55],
                ['id' => 5601, 'name' => 'San Antonio', 'province_id' => 56],
                ['id' => 5602, 'name' => 'Algarrobo', 'province_id' => 56],
                ['id' => 5603, 'name' => 'Cartagena', 'province_id' => 56],
                ['id' => 5604, 'name' => 'El Quisco', 'province_id' => 56],
                ['id' => 5605, 'name' => 'El Tabo', 'province_id' => 56],
                ['id' => 5606, 'name' => 'Santo Domingo', 'province_id' => 56],
                ['id' => 5701, 'name' => 'San Felipe', 'province_id' => 57],
                ['id' => 5702, 'name' => 'Catemu', 'province_id' => 57],
                ['id' => 5703, 'name' => 'Llaillay', 'province_id' => 57],
                ['id' => 5704, 'name' => 'Panquehue', 'province_id' => 57],
                ['id' => 5705, 'name' => 'Putaendo', 'province_id' => 57],
                ['id' => 5706, 'name' => 'Santa María', 'province_id' => 57],
                ['id' => 5801, 'name' => 'Quilpué', 'province_id' => 58],
                ['id' => 5802, 'name' => 'Limache', 'province_id' => 58],
                ['id' => 5803, 'name' => 'Olmué', 'province_id' => 58],
                ['id' => 5804, 'name' => 'Villa Alemana', 'province_id' => 58],
                ['id' => 6101, 'name' => 'Rancagua', 'province_id' => 61],
                ['id' => 6102, 'name' => 'Codegua', 'province_id' => 61],
                ['id' => 6103, 'name' => 'Coinco', 'province_id' => 61],
                ['id' => 6104, 'name' => 'Coltauco', 'province_id' => 61],
                ['id' => 6105, 'name' => 'Doñihue', 'province_id' => 61],
                ['id' => 6106, 'name' => 'Graneros', 'province_id' => 61],
                ['id' => 6107, 'name' => 'Las Cabras', 'province_id' => 61],
                ['id' => 6108, 'name' => 'Machalí', 'province_id' => 61],
                ['id' => 6109, 'name' => 'Malloa', 'province_id' => 61],
                ['id' => 6110, 'name' => 'Mostazal', 'province_id' => 61],
                ['id' => 6111, 'name' => 'Olivar', 'province_id' => 61],
                ['id' => 6112, 'name' => 'Peumo', 'province_id' => 61],
                ['id' => 6113, 'name' => 'Pichidegua', 'province_id' => 61],
                ['id' => 6114, 'name' => 'Quinta de Tilcoco', 'province_id' => 61],
                ['id' => 6115, 'name' => 'Rengo', 'province_id' => 61],
                ['id' => 6116, 'name' => 'Requínoa', 'province_id' => 61],
                ['id' => 6117, 'name' => 'San Vicente', 'province_id' => 61],
                ['id' => 6201, 'name' => 'Pichilemu', 'province_id' => 62],
                ['id' => 6202, 'name' => 'La Estrella', 'province_id' => 62],
                ['id' => 6203, 'name' => 'Litueche', 'province_id' => 62],
                ['id' => 6204, 'name' => 'Marchihue', 'province_id' => 62],
                ['id' => 6205, 'name' => 'Navidad', 'province_id' => 62],
                ['id' => 6206, 'name' => 'Paredones', 'province_id' => 62],
                ['id' => 6301, 'name' => 'San Fernando', 'province_id' => 63],
                ['id' => 6302, 'name' => 'Chépica', 'province_id' => 63],
                ['id' => 6303, 'name' => 'Chimbarongo', 'province_id' => 63],
                ['id' => 6304, 'name' => 'Lolol', 'province_id' => 63],
                ['id' => 6305, 'name' => 'Nancagua', 'province_id' => 63],
                ['id' => 6306, 'name' => 'Palmilla', 'province_id' => 63],
                ['id' => 6307, 'name' => 'Peralillo', 'province_id' => 63],
                ['id' => 6308, 'name' => 'Placilla', 'province_id' => 63],
                ['id' => 6309, 'name' => 'Pumanque', 'province_id' => 63],
                ['id' => 6310, 'name' => 'Santa Cruz', 'province_id' => 63],
                ['id' => 7101, 'name' => 'Talca', 'province_id' => 71],
                ['id' => 7102, 'name' => 'Constitución', 'province_id' => 71],
                ['id' => 7103, 'name' => 'Curepto', 'province_id' => 71],
                ['id' => 7104, 'name' => 'Empedrado', 'province_id' => 71],
                ['id' => 7105, 'name' => 'Maule', 'province_id' => 71],
                ['id' => 7106, 'name' => 'Pelarco', 'province_id' => 71],
                ['id' => 7107, 'name' => 'Pencahue', 'province_id' => 71],
                ['id' => 7108, 'name' => 'Río Claro', 'province_id' => 71],
                ['id' => 7109, 'name' => 'San Clemente', 'province_id' => 71],
                ['id' => 7110, 'name' => 'San Rafael', 'province_id' => 71],
                ['id' => 7201, 'name' => 'Cauquenes', 'province_id' => 72],
                ['id' => 7202, 'name' => 'Chanco', 'province_id' => 72],
                ['id' => 7203, 'name' => 'Pelluhue', 'province_id' => 72],
                ['id' => 7301, 'name' => 'Curicó', 'province_id' => 73],
                ['id' => 7302, 'name' => 'Hualañé', 'province_id' => 73],
                ['id' => 7303, 'name' => 'Licantén', 'province_id' => 73],
                ['id' => 7304, 'name' => 'Molina', 'province_id' => 73],
                ['id' => 7305, 'name' => 'Rauco', 'province_id' => 73],
                ['id' => 7306, 'name' => 'Romeral', 'province_id' => 73],
                ['id' => 7307, 'name' => 'Sagrada Familia', 'province_id' => 73],
                ['id' => 7308, 'name' => 'Teno', 'province_id' => 73],
                ['id' => 7309, 'name' => 'Vichuquén', 'province_id' => 73],
                ['id' => 7401, 'name' => 'Linares', 'province_id' => 74],
                ['id' => 7402, 'name' => 'Colbún', 'province_id' => 74],
                ['id' => 7403, 'name' => 'Longaví', 'province_id' => 74],
                ['id' => 7404, 'name' => 'Parral', 'province_id' => 74],
                ['id' => 7405, 'name' => 'Retiro', 'province_id' => 74],
                ['id' => 7406, 'name' => 'San Javier', 'province_id' => 74],
                ['id' => 7407, 'name' => 'Villa Alegre', 'province_id' => 74],
                ['id' => 7408, 'name' => 'Yerbas Buenas', 'province_id' => 74],
                ['id' => 8101, 'name' => 'Concepción', 'province_id' => 81],
                ['id' => 8102, 'name' => 'Coronel', 'province_id' => 81],
                ['id' => 8103, 'name' => 'Chiguayante', 'province_id' => 81],
                ['id' => 8104, 'name' => 'Florida', 'province_id' => 81],
                ['id' => 8105, 'name' => 'Hualqui', 'province_id' => 81],
                ['id' => 8106, 'name' => 'Lota', 'province_id' => 81],
                ['id' => 8107, 'name' => 'Penco', 'province_id' => 81],
                ['id' => 8108, 'name' => 'San Pedro de la Paz', 'province_id' => 81],
                ['id' => 8109, 'name' => 'Santa Juana', 'province_id' => 81],
                ['id' => 8110, 'name' => 'Talcahuano', 'province_id' => 81],
                ['id' => 8111, 'name' => 'Tomé', 'province_id' => 81],
                ['id' => 8112, 'name' => 'Hualpén', 'province_id' => 81],
                ['id' => 8201, 'name' => 'Lebu', 'province_id' => 82],
                ['id' => 8202, 'name' => 'Arauco', 'province_id' => 82],
                ['id' => 8203, 'name' => 'Cañete', 'province_id' => 82],
                ['id' => 8204, 'name' => 'Contulmo', 'province_id' => 82],
                ['id' => 8205, 'name' => 'Curanilahue', 'province_id' => 82],
                ['id' => 8206, 'name' => 'Los Alamos', 'province_id' => 82],
                ['id' => 8207, 'name' => 'Tirúa', 'province_id' => 82],
                ['id' => 8301, 'name' => 'Los Angeles', 'province_id' => 83],
                ['id' => 8302, 'name' => 'Antuco', 'province_id' => 83],
                ['id' => 8303, 'name' => 'Cabrero', 'province_id' => 83],
                ['id' => 8304, 'name' => 'Laja', 'province_id' => 83],
                ['id' => 8305, 'name' => 'Mulchén', 'province_id' => 83],
                ['id' => 8306, 'name' => 'Nacimiento', 'province_id' => 83],
                ['id' => 8307, 'name' => 'Negrete', 'province_id' => 83],
                ['id' => 8308, 'name' => 'Quilaco', 'province_id' => 83],
                ['id' => 8309, 'name' => 'Quilleco', 'province_id' => 83],
                ['id' => 8310, 'name' => 'San Rosendo', 'province_id' => 83],
                ['id' => 8311, 'name' => 'Santa Bárbara', 'province_id' => 83],
                ['id' => 8312, 'name' => 'Tucapel', 'province_id' => 83],
                ['id' => 8313, 'name' => 'Yumbel', 'province_id' => 83],
                ['id' => 8314, 'name' => 'Alto Biobío', 'province_id' => 83],
                ['id' => 9101, 'name' => 'Temuco', 'province_id' => 91],
                ['id' => 9102, 'name' => 'Carahue', 'province_id' => 91],
                ['id' => 9103, 'name' => 'Cunco', 'province_id' => 91],
                ['id' => 9104, 'name' => 'Curarrehue', 'province_id' => 91],
                ['id' => 9105, 'name' => 'Freire', 'province_id' => 91],
                ['id' => 9106, 'name' => 'Galvarino', 'province_id' => 91],
                ['id' => 9107, 'name' => 'Gorbea', 'province_id' => 91],
                ['id' => 9108, 'name' => 'Lautaro', 'province_id' => 91],
                ['id' => 9109, 'name' => 'Loncoche', 'province_id' => 91],
                ['id' => 9110, 'name' => 'Melipeuco', 'province_id' => 91],
                ['id' => 9111, 'name' => 'Nueva Imperial', 'province_id' => 91],
                ['id' => 9112, 'name' => 'Padre Las Casas', 'province_id' => 91],
                ['id' => 9113, 'name' => 'Perquenco', 'province_id' => 91],
                ['id' => 9114, 'name' => 'Pitrufquén', 'province_id' => 91],
                ['id' => 9115, 'name' => 'Pucón', 'province_id' => 91],
                ['id' => 9116, 'name' => 'Saavedra', 'province_id' => 91],
                ['id' => 9117, 'name' => 'Teodoro Schmidt', 'province_id' => 91],
                ['id' => 9118, 'name' => 'Toltén', 'province_id' => 91],
                ['id' => 9119, 'name' => 'Vilcún', 'province_id' => 91],
                ['id' => 9120, 'name' => 'Villarrica', 'province_id' => 91],
                ['id' => 9121, 'name' => 'Cholchol', 'province_id' => 91],
                ['id' => 9201, 'name' => 'Angol', 'province_id' => 92],
                ['id' => 9202, 'name' => 'Collipulli', 'province_id' => 92],
                ['id' => 9203, 'name' => 'Curacautín', 'province_id' => 92],
                ['id' => 9204, 'name' => 'Ercilla', 'province_id' => 92],
                ['id' => 9205, 'name' => 'Lonquimay', 'province_id' => 92],
                ['id' => 9206, 'name' => 'Los Sauces', 'province_id' => 92],
                ['id' => 9207, 'name' => 'Lumaco', 'province_id' => 92],
                ['id' => 9208, 'name' => 'Purén', 'province_id' => 92],
                ['id' => 9209, 'name' => 'Renaico', 'province_id' => 92],
                ['id' => 9210, 'name' => 'Traiguén', 'province_id' => 92],
                ['id' => 9211, 'name' => 'Victoria', 'province_id' => 92],
                ['id' => 10101, 'name' => 'Puerto Montt', 'province_id' => 101],
                ['id' => 10102, 'name' => 'Calbuco', 'province_id' => 101],
                ['id' => 10103, 'name' => 'Cochamó', 'province_id' => 101],
                ['id' => 10104, 'name' => 'Fresia', 'province_id' => 101],
                ['id' => 10105, 'name' => 'Frutillar', 'province_id' => 101],
                ['id' => 10106, 'name' => 'Los Muermos', 'province_id' => 101],
                ['id' => 10107, 'name' => 'Llanquihue', 'province_id' => 101],
                ['id' => 10108, 'name' => 'Maullín', 'province_id' => 101],
                ['id' => 10109, 'name' => 'Puerto Varas', 'province_id' => 101],
                ['id' => 10201, 'name' => 'Castro', 'province_id' => 102],
                ['id' => 10202, 'name' => 'Ancud', 'province_id' => 102],
                ['id' => 10203, 'name' => 'Chonchi', 'province_id' => 102],
                ['id' => 10204, 'name' => 'Curaco de Vélez', 'province_id' => 102],
                ['id' => 10205, 'name' => 'Dalcahue', 'province_id' => 102],
                ['id' => 10206, 'name' => 'Puqueldón', 'province_id' => 102],
                ['id' => 10207, 'name' => 'Queilén', 'province_id' => 102],
                ['id' => 10208, 'name' => 'Quellón', 'province_id' => 102],
                ['id' => 10209, 'name' => 'Quemchi', 'province_id' => 102],
                ['id' => 10210, 'name' => 'Quinchao', 'province_id' => 102],
                ['id' => 10301, 'name' => 'Osorno', 'province_id' => 103],
                ['id' => 10302, 'name' => 'Puerto Octay', 'province_id' => 103],
                ['id' => 10303, 'name' => 'Purranque', 'province_id' => 103],
                ['id' => 10304, 'name' => 'Puyehue', 'province_id' => 103],
                ['id' => 10305, 'name' => 'Río Negro', 'province_id' => 103],
                ['id' => 10306, 'name' => 'San Juan de la Costa', 'province_id' => 103],
                ['id' => 10307, 'name' => 'San Pablo', 'province_id' => 103],
                ['id' => 10401, 'name' => 'Chaitén', 'province_id' => 104],
                ['id' => 10402, 'name' => 'Futaleufú', 'province_id' => 104],
                ['id' => 10403, 'name' => 'Hualaihué', 'province_id' => 104],
                ['id' => 10404, 'name' => 'Palena', 'province_id' => 104],
                ['id' => 11101, 'name' => 'Coyhaique', 'province_id' => 111],
                ['id' => 11102, 'name' => 'Lago Verde', 'province_id' => 111],
                ['id' => 11201, 'name' => 'Aysén', 'province_id' => 112],
                ['id' => 11202, 'name' => 'Cisnes', 'province_id' => 112],
                ['id' => 11203, 'name' => 'Guaitecas', 'province_id' => 112],
                ['id' => 11301, 'name' => 'Cochrane', 'province_id' => 113],
                ['id' => 11302, 'name' => 'O Higgins', 'province_id' => 113],
                ['id' => 11303, 'name' => 'Tortel', 'province_id' => 113],
                ['id' => 11401, 'name' => 'Chile Chico', 'province_id' => 114],
                ['id' => 11402, 'name' => 'Río Ibáñez', 'province_id' => 114],
                ['id' => 12101, 'name' => 'Punta Arenas', 'province_id' => 121],
                ['id' => 12102, 'name' => 'Laguna Blanca', 'province_id' => 121],
                ['id' => 12103, 'name' => 'Río Verde', 'province_id' => 121],
                ['id' => 12104, 'name' => 'San Gregorio', 'province_id' => 121],
                ['id' => 12201, 'name' => 'Cabo de Hornos', 'province_id' => 122],
                ['id' => 12202, 'name' => 'Antártica', 'province_id' => 122],
                ['id' => 12301, 'name' => 'Porvenir', 'province_id' => 123],
                ['id' => 12302, 'name' => 'Primavera', 'province_id' => 123],
                ['id' => 12303, 'name' => 'Timaukel', 'province_id' => 123],
                ['id' => 12401, 'name' => 'Natales', 'province_id' => 124],
                ['id' => 12402, 'name' => 'Torres del Paine', 'province_id' => 124],
                ['id' => 13101, 'name' => 'Santiago', 'province_id' => 131],
                ['id' => 13102, 'name' => 'Cerrillos', 'province_id' => 131],
                ['id' => 13103, 'name' => 'Cerro Navia', 'province_id' => 131],
                ['id' => 13104, 'name' => 'Conchalí', 'province_id' => 131],
                ['id' => 13105, 'name' => 'El Bosque', 'province_id' => 131],
                ['id' => 13106, 'name' => 'Estación Central', 'province_id' => 131],
                ['id' => 13107, 'name' => 'Huechuraba', 'province_id' => 131],
                ['id' => 13108, 'name' => 'Independencia', 'province_id' => 131],
                ['id' => 13109, 'name' => 'La Cisterna', 'province_id' => 131],
                ['id' => 13110, 'name' => 'La Florida', 'province_id' => 131],
                ['id' => 13111, 'name' => 'La Granja', 'province_id' => 131],
                ['id' => 13112, 'name' => 'La Pintana', 'province_id' => 131],
                ['id' => 13113, 'name' => 'La Reina', 'province_id' => 131],
                ['id' => 13114, 'name' => 'Las Condes', 'province_id' => 131],
                ['id' => 13115, 'name' => 'Lo Barnechea', 'province_id' => 131],
                ['id' => 13116, 'name' => 'Lo Espejo', 'province_id' => 131],
                ['id' => 13117, 'name' => 'Lo Prado', 'province_id' => 131],
                ['id' => 13118, 'name' => 'Macul', 'province_id' => 131],
                ['id' => 13119, 'name' => 'Maipú', 'province_id' => 131],
                ['id' => 13120, 'name' => 'Ñuñoa', 'province_id' => 131],
                ['id' => 13121, 'name' => 'Pedro Aguirre Cerda', 'province_id' => 131],
                ['id' => 13122, 'name' => 'Peñalolén', 'province_id' => 131],
                ['id' => 13123, 'name' => 'Providencia', 'province_id' => 131],
                ['id' => 13124, 'name' => 'Pudahuel', 'province_id' => 131],
                ['id' => 13125, 'name' => 'Quilicura', 'province_id' => 131],
                ['id' => 13126, 'name' => 'Quinta Normal', 'province_id' => 131],
                ['id' => 13127, 'name' => 'Recoleta', 'province_id' => 131],
                ['id' => 13128, 'name' => 'Renca', 'province_id' => 131],
                ['id' => 13129, 'name' => 'San Joaquín', 'province_id' => 131],
                ['id' => 13130, 'name' => 'San Miguel', 'province_id' => 131],
                ['id' => 13131, 'name' => 'San Ramón', 'province_id' => 131],
                ['id' => 13132, 'name' => 'Vitacura', 'province_id' => 131],
                ['id' => 13201, 'name' => 'Puente Alto', 'province_id' => 132],
                ['id' => 13202, 'name' => 'Pirque', 'province_id' => 132],
                ['id' => 13203, 'name' => 'San José de Maipo', 'province_id' => 132],
                ['id' => 13301, 'name' => 'Colina', 'province_id' => 133],
                ['id' => 13302, 'name' => 'Lampa', 'province_id' => 133],
                ['id' => 13303, 'name' => 'Tiltil', 'province_id' => 133],
                ['id' => 13401, 'name' => 'San Bernardo', 'province_id' => 134],
                ['id' => 13402, 'name' => 'Buin', 'province_id' => 134],
                ['id' => 13403, 'name' => 'Calera de Tango', 'province_id' => 134],
                ['id' => 13404, 'name' => 'Paine', 'province_id' => 134],
                ['id' => 13501, 'name' => 'Melipilla', 'province_id' => 135],
                ['id' => 13502, 'name' => 'Alhué', 'province_id' => 135],
                ['id' => 13503, 'name' => 'Curacaví', 'province_id' => 135],
                ['id' => 13504, 'name' => 'María Pinto', 'province_id' => 135],
                ['id' => 13505, 'name' => 'San Pedro', 'province_id' => 135],
                ['id' => 13601, 'name' => 'Talagante', 'province_id' => 136],
                ['id' => 13602, 'name' => 'El Monte', 'province_id' => 136],
                ['id' => 13603, 'name' => 'Isla de Maipo', 'province_id' => 136],
                ['id' => 13604, 'name' => 'Padre Hurtado', 'province_id' => 136],
                ['id' => 13605, 'name' => 'Peñaflor', 'province_id' => 136],
                ['id' => 14101, 'name' => 'Valdivia', 'province_id' => 141],
                ['id' => 14102, 'name' => 'Corral', 'province_id' => 141],
                ['id' => 14103, 'name' => 'Lanco', 'province_id' => 141],
                ['id' => 14104, 'name' => 'Los Lagos', 'province_id' => 141],
                ['id' => 14105, 'name' => 'Máfil', 'province_id' => 141],
                ['id' => 14106, 'name' => 'Mariquina', 'province_id' => 141],
                ['id' => 14107, 'name' => 'Paillaco', 'province_id' => 141],
                ['id' => 14108, 'name' => 'Panguipulli', 'province_id' => 141],
                ['id' => 14201, 'name' => 'La Unión', 'province_id' => 142],
                ['id' => 14202, 'name' => 'Futrono', 'province_id' => 142],
                ['id' => 14203, 'name' => 'Lago Ranco', 'province_id' => 142],
                ['id' => 14204, 'name' => 'Río Bueno', 'province_id' => 142],
                ['id' => 15101, 'name' => 'Arica', 'province_id' => 151],
                ['id' => 15102, 'name' => 'Camarones', 'province_id' => 151],
                ['id' => 15201, 'name' => 'Putre', 'province_id' => 152],
                ['id' => 15202, 'name' => 'General Lagos', 'province_id' => 152],
                ['id' => 16101, 'name' => 'Chillán', 'province_id' => 161],
                ['id' => 16102, 'name' => 'Bulnes', 'province_id' => 161],
                ['id' => 16103, 'name' => 'Chillán Viejo', 'province_id' => 161],
                ['id' => 16104, 'name' => 'El Carmen', 'province_id' => 161],
                ['id' => 16105, 'name' => 'Pemuco', 'province_id' => 161],
                ['id' => 16106, 'name' => 'Pinto', 'province_id' => 161],
                ['id' => 16107, 'name' => 'Quillón', 'province_id' => 161],
                ['id' => 16108, 'name' => 'San Ignacio', 'province_id' => 161],
                ['id' => 16109, 'name' => 'Yungay', 'province_id' => 161],
                ['id' => 16201, 'name' => 'Quirihue', 'province_id' => 162],
                ['id' => 16202, 'name' => 'Cobquecura', 'province_id' => 162],
                ['id' => 16203, 'name' => 'Coelemu', 'province_id' => 162],
                ['id' => 16204, 'name' => 'Ninhue', 'province_id' => 162],
                ['id' => 16205, 'name' => 'Portezuelo', 'province_id' => 162],
                ['id' => 16206, 'name' => 'Ranquil', 'province_id' => 162],
                ['id' => 16207, 'name' => 'Treguaco', 'province_id' => 162],
                ['id' => 16301, 'name' => 'San Carlos', 'province_id' => 163],
                ['id' => 16302, 'name' => 'Coihueco', 'province_id' => 163],
                ['id' => 16303, 'name' => 'Ñiquén', 'province_id' => 163],
                ['id' => 16304, 'name' => 'San Fabián', 'province_id' => 163],
                ['id' => 16305, 'name' => 'San Nicolás', 'province_id' => 163],
            ]
        );

        $this->command->info("✅ Comunas insertadas correctamente.");
        $this->command->info("Todas las comunas de chile han sido insertadas en la base de datos. (Actualizado a 16/10/2025)");
    }
}

