version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    container_name: erp-app
    restart: unless-stopped
    env_file: .env
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      APP_PORT: 8000
      TZ: America/Santiago
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: zentriaback
      DB_USERNAME: postgres
      DB_PASSWORD: root
      RUN_MIGRATIONS: "true"
      RUN_SEED: "false"
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: erp-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: zentriaback
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      TZ: America/Santiago
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
